const GOOGLE_API_KEY = import.meta.env.VITE_GOOGLE_API_KEY

const EMAILJS_SERVICEID = import.meta.env.VITE_EMAILJS_SERVICEID
const EMAILJS_TEMPLATEID = import.meta.env.VITE_EMAILJS_TEMPLATEID
const EMAILJS_PUBLICKEY = import.meta.env.VITE_EMAILJS_PUBLICKEY

export default {
  GOOGLE_API_KEY,
  EMAILJS_SERVICEID,
  EMAILJS_TEMPLATEID,
  EMAILJS_PUBLICKEY,
}
